/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutUsContent {
  'title' : string,
  'content' : string,
  'mission' : [] | [string],
  'teamImage' : [] | [ExternalBlob],
  'vision' : [] | [string],
}
export interface ContactInfo {
  'whatsapp' : [] | [string],
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : bigint,
  'order' : bigint,
  'caption' : [] | [string],
  'category' : [] | [string],
  'image' : ExternalBlob,
}
export interface HeroSlide {
  'id' : bigint,
  'order' : bigint,
  'caption' : [] | [string],
  'image' : ExternalBlob,
}
export interface PolicyContent {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'slug' : string,
  'lastUpdated' : bigint,
}
export interface Property {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'amenities' : Array<string>,
  'highlights' : Array<string>,
  'heroImage' : [] | [ExternalBlob],
  'bookingUrl' : [] | [string],
  'location' : string,
}
export interface PropertyGalleryImage {
  'id' : bigint,
  'order' : bigint,
  'propertyId' : string,
  'caption' : [] | [string],
  'image' : ExternalBlob,
}
export interface RoomType {
  'id' : bigint,
  'thumbnail' : [] | [ExternalBlob],
  'pricePerNight' : [] | [string],
  'name' : string,
  'description' : string,
  'propertyId' : bigint,
  'amenities' : Array<string>,
  'capacity' : [] | [string],
}
export interface SiteSettings {
  'contactInfo' : ContactInfo,
  'socialLinks' : Array<SocialLink>,
  'logo' : [] | [ExternalBlob],
  'bookingUrl' : [] | [string],
  'footerText' : string,
}
export interface SocialLink { 'url' : string, 'platform' : string }
export interface Testimonial {
  'id' : bigint,
  'name' : string,
  'text' : string,
  'isActive' : boolean,
  'rating' : bigint,
  'location' : [] | [string],
  'avatar' : [] | [ExternalBlob],
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '__contentState' : ActorMethod<[], any>,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage, string, string], undefined>,
  'addHeroSlide' : ActorMethod<[HeroSlide, string, string], undefined>,
  'addProperty' : ActorMethod<[Property, string, string], undefined>,
  'addPropertyGalleryImage' : ActorMethod<
    [PropertyGalleryImage, string, string],
    undefined
  >,
  'addRoomType' : ActorMethod<[RoomType, string, string], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial, string, string], undefined>,
  'getAboutUs' : ActorMethod<[], AboutUsContent>,
  'getAllTestimonials' : ActorMethod<[string, string], Array<Testimonial>>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getHeroSlides' : ActorMethod<[], Array<HeroSlide>>,
  'getNextId' : ActorMethod<[], bigint>,
  'getPolicies' : ActorMethod<[], Array<PolicyContent>>,
  'getPolicyBySlug' : ActorMethod<[string], [] | [PolicyContent]>,
  'getProperties' : ActorMethod<[], Array<Property>>,
  'getPropertyGalleryImages' : ActorMethod<
    [string],
    Array<PropertyGalleryImage>
  >,
  'getRoomTypes' : ActorMethod<[], Array<RoomType>>,
  'getRoomTypesByProperty' : ActorMethod<[bigint], Array<RoomType>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'login' : ActorMethod<[string, string], boolean>,
  'removeGalleryImage' : ActorMethod<[bigint, string, string], undefined>,
  'removeHeroSlide' : ActorMethod<[bigint, string, string], undefined>,
  'removeProperty' : ActorMethod<[bigint, string, string], undefined>,
  'removePropertyGalleryImage' : ActorMethod<
    [bigint, string, string],
    undefined
  >,
  'removeRoomType' : ActorMethod<[bigint, string, string], undefined>,
  'removeTestimonial' : ActorMethod<[bigint, string, string], undefined>,
  'setAboutUs' : ActorMethod<[AboutUsContent, string, string], undefined>,
  'setPolicy' : ActorMethod<[PolicyContent, string, string], undefined>,
  'setSiteSettings' : ActorMethod<[SiteSettings, string, string], undefined>,
  'updateGalleryImage' : ActorMethod<[GalleryImage, string, string], undefined>,
  'updateHeroSlide' : ActorMethod<[HeroSlide, string, string], undefined>,
  'updateProperty' : ActorMethod<[Property, string, string], undefined>,
  'updateRoomType' : ActorMethod<[RoomType, string, string], undefined>,
  'updateTestimonial' : ActorMethod<[Testimonial, string, string], undefined>,
  'verifyAdmin' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];