/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'caption' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'image' : ExternalBlob,
});
export const HeroSlide = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'caption' : IDL.Opt(IDL.Text),
  'image' : ExternalBlob,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'highlights' : IDL.Vec(IDL.Text),
  'heroImage' : IDL.Opt(ExternalBlob),
  'bookingUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const PropertyGalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'propertyId' : IDL.Text,
  'caption' : IDL.Opt(IDL.Text),
  'image' : ExternalBlob,
});
export const RoomType = IDL.Record({
  'id' : IDL.Nat,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'pricePerNight' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'propertyId' : IDL.Nat,
  'amenities' : IDL.Vec(IDL.Text),
  'capacity' : IDL.Opt(IDL.Text),
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'text' : IDL.Text,
  'isActive' : IDL.Bool,
  'rating' : IDL.Nat,
  'location' : IDL.Opt(IDL.Text),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const AboutUsContent = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'mission' : IDL.Opt(IDL.Text),
  'teamImage' : IDL.Opt(ExternalBlob),
  'vision' : IDL.Opt(IDL.Text),
});
export const PolicyContent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'slug' : IDL.Text,
  'lastUpdated' : IDL.Int,
});
export const ContactInfo = IDL.Record({
  'whatsapp' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'contactInfo' : ContactInfo,
  'socialLinks' : IDL.Vec(SocialLink),
  'logo' : IDL.Opt(ExternalBlob),
  'bookingUrl' : IDL.Opt(IDL.Text),
  'footerText' : IDL.Text,
});

export const idlService = IDL.Service({
  '__contentState' : IDL.Func([], [IDL.Reserved], ['query']),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addGalleryImage' : IDL.Func([GalleryImage, IDL.Text, IDL.Text], [], []),
  'addHeroSlide' : IDL.Func([HeroSlide, IDL.Text, IDL.Text], [], []),
  'addProperty' : IDL.Func([Property, IDL.Text, IDL.Text], [], []),
  'addPropertyGalleryImage' : IDL.Func(
      [PropertyGalleryImage, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addRoomType' : IDL.Func([RoomType, IDL.Text, IDL.Text], [], []),
  'addTestimonial' : IDL.Func([Testimonial, IDL.Text, IDL.Text], [], []),
  'getAboutUs' : IDL.Func([], [AboutUsContent], ['query']),
  'getAllTestimonials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Testimonial)],
      [],
    ),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getHeroSlides' : IDL.Func([], [IDL.Vec(HeroSlide)], ['query']),
  'getNextId' : IDL.Func([], [IDL.Nat], ['query']),
  'getPolicies' : IDL.Func([], [IDL.Vec(PolicyContent)], ['query']),
  'getPolicyBySlug' : IDL.Func([IDL.Text], [IDL.Opt(PolicyContent)], ['query']),
  'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getPropertyGalleryImages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PropertyGalleryImage)],
      ['query'],
    ),
  'getRoomTypes' : IDL.Func([], [IDL.Vec(RoomType)], ['query']),
  'getRoomTypesByProperty' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RoomType)],
      ['query'],
    ),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'removeGalleryImage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'removeHeroSlide' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'removeProperty' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'removePropertyGalleryImage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'removeRoomType' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'removeTestimonial' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'setAboutUs' : IDL.Func([AboutUsContent, IDL.Text, IDL.Text], [], []),
  'setPolicy' : IDL.Func([PolicyContent, IDL.Text, IDL.Text], [], []),
  'setSiteSettings' : IDL.Func([SiteSettings, IDL.Text, IDL.Text], [], []),
  'updateGalleryImage' : IDL.Func([GalleryImage, IDL.Text, IDL.Text], [], []),
  'updateHeroSlide' : IDL.Func([HeroSlide, IDL.Text, IDL.Text], [], []),
  'updateProperty' : IDL.Func([Property, IDL.Text, IDL.Text], [], []),
  'updateRoomType' : IDL.Func([RoomType, IDL.Text, IDL.Text], [], []),
  'updateTestimonial' : IDL.Func([Testimonial, IDL.Text, IDL.Text], [], []),
  'verifyAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'caption' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'image' : ExternalBlob,
  });
  const HeroSlide = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'caption' : IDL.Opt(IDL.Text),
    'image' : ExternalBlob,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'highlights' : IDL.Vec(IDL.Text),
    'heroImage' : IDL.Opt(ExternalBlob),
    'bookingUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const PropertyGalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'propertyId' : IDL.Text,
    'caption' : IDL.Opt(IDL.Text),
    'image' : ExternalBlob,
  });
  const RoomType = IDL.Record({
    'id' : IDL.Nat,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'pricePerNight' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'propertyId' : IDL.Nat,
    'amenities' : IDL.Vec(IDL.Text),
    'capacity' : IDL.Opt(IDL.Text),
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'text' : IDL.Text,
    'isActive' : IDL.Bool,
    'rating' : IDL.Nat,
    'location' : IDL.Opt(IDL.Text),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const AboutUsContent = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'mission' : IDL.Opt(IDL.Text),
    'teamImage' : IDL.Opt(ExternalBlob),
    'vision' : IDL.Opt(IDL.Text),
  });
  const PolicyContent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'slug' : IDL.Text,
    'lastUpdated' : IDL.Int,
  });
  const ContactInfo = IDL.Record({
    'whatsapp' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  const SiteSettings = IDL.Record({
    'contactInfo' : ContactInfo,
    'socialLinks' : IDL.Vec(SocialLink),
    'logo' : IDL.Opt(ExternalBlob),
    'bookingUrl' : IDL.Opt(IDL.Text),
    'footerText' : IDL.Text,
  });
  
  return IDL.Service({
    '__contentState' : IDL.Func([], [IDL.Reserved], ['query']),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addGalleryImage' : IDL.Func([GalleryImage, IDL.Text, IDL.Text], [], []),
    'addHeroSlide' : IDL.Func([HeroSlide, IDL.Text, IDL.Text], [], []),
    'addProperty' : IDL.Func([Property, IDL.Text, IDL.Text], [], []),
    'addPropertyGalleryImage' : IDL.Func(
        [PropertyGalleryImage, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addRoomType' : IDL.Func([RoomType, IDL.Text, IDL.Text], [], []),
    'addTestimonial' : IDL.Func([Testimonial, IDL.Text, IDL.Text], [], []),
    'getAboutUs' : IDL.Func([], [AboutUsContent], ['query']),
    'getAllTestimonials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Testimonial)],
        [],
      ),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getHeroSlides' : IDL.Func([], [IDL.Vec(HeroSlide)], ['query']),
    'getNextId' : IDL.Func([], [IDL.Nat], ['query']),
    'getPolicies' : IDL.Func([], [IDL.Vec(PolicyContent)], ['query']),
    'getPolicyBySlug' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PolicyContent)],
        ['query'],
      ),
    'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getPropertyGalleryImages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PropertyGalleryImage)],
        ['query'],
      ),
    'getRoomTypes' : IDL.Func([], [IDL.Vec(RoomType)], ['query']),
    'getRoomTypesByProperty' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RoomType)],
        ['query'],
      ),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'removeGalleryImage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'removeHeroSlide' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'removeProperty' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'removePropertyGalleryImage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'removeRoomType' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'removeTestimonial' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'setAboutUs' : IDL.Func([AboutUsContent, IDL.Text, IDL.Text], [], []),
    'setPolicy' : IDL.Func([PolicyContent, IDL.Text, IDL.Text], [], []),
    'setSiteSettings' : IDL.Func([SiteSettings, IDL.Text, IDL.Text], [], []),
    'updateGalleryImage' : IDL.Func([GalleryImage, IDL.Text, IDL.Text], [], []),
    'updateHeroSlide' : IDL.Func([HeroSlide, IDL.Text, IDL.Text], [], []),
    'updateProperty' : IDL.Func([Property, IDL.Text, IDL.Text], [], []),
    'updateRoomType' : IDL.Func([RoomType, IDL.Text, IDL.Text], [], []),
    'updateTestimonial' : IDL.Func([Testimonial, IDL.Text, IDL.Text], [], []),
    'verifyAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };