/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PolicyContent {
    id: bigint;
    title: string;
    body: string;
    slug: string;
    lastUpdated: bigint;
}
export interface SocialLink {
    url: string;
    platform: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RoomType {
    id: bigint;
    thumbnail?: ExternalBlob;
    pricePerNight?: string;
    name: string;
    description: string;
    propertyId: bigint;
    amenities: Array<string>;
    capacity?: string;
}
export interface HeroSlide {
    id: bigint;
    order: bigint;
    caption?: string;
    image: ExternalBlob;
}
export interface AboutUsContent {
    title: string;
    content: string;
    mission?: string;
    teamImage?: ExternalBlob;
    vision?: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Property {
    id: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    highlights: Array<string>;
    heroImage?: ExternalBlob;
    bookingUrl?: string;
    location: string;
}
export interface SiteSettings {
    contactInfo: ContactInfo;
    socialLinks: Array<SocialLink>;
    logo?: ExternalBlob;
    bookingUrl?: string;
    footerText: string;
}
export interface GalleryImage {
    id: bigint;
    order: bigint;
    caption?: string;
    category?: string;
    image: ExternalBlob;
}
export interface ContactInfo {
    whatsapp?: string;
    email: string;
    address: string;
    phone: string;
}
export interface Testimonial {
    id: bigint;
    name: string;
    text: string;
    isActive: boolean;
    rating: bigint;
    location?: string;
    avatar?: ExternalBlob;
}
export interface backendInterface {
    __contentState(): Promise<any>;
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addGalleryImage(image: GalleryImage, email: string, password: string): Promise<void>;
    addHeroSlide(slide: HeroSlide, email: string, password: string): Promise<void>;
    addProperty(property: Property, email: string, password: string): Promise<void>;
    addRoomType(room: RoomType, email: string, password: string): Promise<void>;
    addTestimonial(testimonial: Testimonial, email: string, password: string): Promise<void>;
    getAboutUs(): Promise<AboutUsContent>;
    getAllTestimonials(email: string, password: string): Promise<Array<Testimonial>>;
    getGalleryImages(): Promise<Array<GalleryImage>>;
    getHeroSlides(): Promise<Array<HeroSlide>>;
    getNextId(): Promise<bigint>;
    getPolicies(): Promise<Array<PolicyContent>>;
    getPolicyBySlug(slug: string): Promise<PolicyContent | null>;
    getProperties(): Promise<Array<Property>>;
    getRoomTypes(): Promise<Array<RoomType>>;
    getRoomTypesByProperty(propertyId: bigint): Promise<Array<RoomType>>;
    getSiteSettings(): Promise<SiteSettings>;
    getTestimonials(): Promise<Array<Testimonial>>;
    login(email: string, password: string): Promise<boolean>;
    removeGalleryImage(id: bigint, email: string, password: string): Promise<void>;
    removeHeroSlide(id: bigint, email: string, password: string): Promise<void>;
    removeProperty(id: bigint, email: string, password: string): Promise<void>;
    removeRoomType(id: bigint, email: string, password: string): Promise<void>;
    removeTestimonial(id: bigint, email: string, password: string): Promise<void>;
    setAboutUs(content: AboutUsContent, email: string, password: string): Promise<void>;
    setPolicy(policy: PolicyContent, email: string, password: string): Promise<void>;
    setSiteSettings(settings: SiteSettings, email: string, password: string): Promise<void>;
    updateGalleryImage(image: GalleryImage, email: string, password: string): Promise<void>;
    updateHeroSlide(slide: HeroSlide, email: string, password: string): Promise<void>;
    updateProperty(property: Property, email: string, password: string): Promise<void>;
    updateRoomType(room: RoomType, email: string, password: string): Promise<void>;
    updateTestimonial(testimonial: Testimonial, email: string, password: string): Promise<void>;
    verifyAdmin(email: string, password: string): Promise<boolean>;
}
import type { AboutUsContent as _AboutUsContent, ContactInfo as _ContactInfo, ExternalBlob as _ExternalBlob, GalleryImage as _GalleryImage, HeroSlide as _HeroSlide, PolicyContent as _PolicyContent, Property as _Property, RoomType as _RoomType, SiteSettings as _SiteSettings, SocialLink as _SocialLink, Testimonial as _Testimonial, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __contentState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__contentState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__contentState();
            return result;
        }
    }
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addGalleryImage(arg0: GalleryImage, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(await to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(await to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async addHeroSlide(arg0: HeroSlide, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHeroSlide(await to_candid_HeroSlide_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHeroSlide(await to_candid_HeroSlide_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async addProperty(arg0: Property, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProperty(await to_candid_Property_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProperty(await to_candid_Property_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async addRoomType(arg0: RoomType, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoomType(await to_candid_RoomType_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoomType(await to_candid_RoomType_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async addTestimonial(arg0: Testimonial, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(await to_candid_Testimonial_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(await to_candid_Testimonial_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async getAboutUs(): Promise<AboutUsContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getAboutUs();
                return from_candid_AboutUsContent_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAboutUs();
            return from_candid_AboutUsContent_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestimonials(arg0: string, arg1: string): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials(arg0, arg1);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials(arg0, arg1);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImages();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImages();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeroSlides(): Promise<Array<HeroSlide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeroSlides();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeroSlides();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextId();
            return result;
        }
    }
    async getPolicies(): Promise<Array<PolicyContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolicies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolicies();
            return result;
        }
    }
    async getPolicyBySlug(arg0: string): Promise<PolicyContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPolicyBySlug(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPolicyBySlug(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperties();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperties();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomTypes(): Promise<Array<RoomType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomTypes();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomTypes();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomTypesByProperty(arg0: bigint): Promise<Array<RoomType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomTypesByProperty(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomTypesByProperty(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return from_candid_SiteSettings_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return from_candid_SiteSettings_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return result;
        }
    }
    async removeGalleryImage(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGalleryImage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGalleryImage(arg0, arg1, arg2);
            return result;
        }
    }
    async removeHeroSlide(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeHeroSlide(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeHeroSlide(arg0, arg1, arg2);
            return result;
        }
    }
    async removeProperty(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProperty(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProperty(arg0, arg1, arg2);
            return result;
        }
    }
    async removeRoomType(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeRoomType(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeRoomType(arg0, arg1, arg2);
            return result;
        }
    }
    async removeTestimonial(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTestimonial(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTestimonial(arg0, arg1, arg2);
            return result;
        }
    }
    async setAboutUs(arg0: AboutUsContent, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAboutUs(await to_candid_AboutUsContent_n44(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAboutUs(await to_candid_AboutUsContent_n44(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async setPolicy(arg0: PolicyContent, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPolicy(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPolicy(arg0, arg1, arg2);
            return result;
        }
    }
    async setSiteSettings(arg0: SiteSettings, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSiteSettings(await to_candid_SiteSettings_n46(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSiteSettings(await to_candid_SiteSettings_n46(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async updateGalleryImage(arg0: GalleryImage, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryImage(await to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryImage(await to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async updateHeroSlide(arg0: HeroSlide, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeroSlide(await to_candid_HeroSlide_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeroSlide(await to_candid_HeroSlide_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async updateProperty(arg0: Property, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(await to_candid_Property_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(await to_candid_Property_n13(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async updateRoomType(arg0: RoomType, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoomType(await to_candid_RoomType_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoomType(await to_candid_RoomType_n15(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async updateTestimonial(arg0: Testimonial, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(await to_candid_Testimonial_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(await to_candid_Testimonial_n17(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async verifyAdmin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdmin(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_AboutUsContent_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AboutUsContent): Promise<AboutUsContent> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ContactInfo_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactInfo): ContactInfo {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryImage_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryImage): Promise<GalleryImage> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_HeroSlide_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeroSlide): Promise<HeroSlide> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Property_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Promise<Property> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_RoomType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): Promise<RoomType> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_SiteSettings_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteSettings): Promise<SiteSettings> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_Testimonial_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimonial): Promise<Testimonial> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PolicyContent]): PolicyContent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    mission: [] | [string];
    teamImage: [] | [_ExternalBlob];
    vision: [] | [string];
}): Promise<{
    title: string;
    content: string;
    mission?: string;
    teamImage?: ExternalBlob;
    vision?: string;
}> {
    return {
        title: value.title,
        content: value.content,
        mission: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.mission)),
        teamImage: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.teamImage)),
        vision: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.vision))
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    text: string;
    isActive: boolean;
    rating: bigint;
    location: [] | [string];
    avatar: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    name: string;
    text: string;
    isActive: boolean;
    rating: bigint;
    location?: string;
    avatar?: ExternalBlob;
}> {
    return {
        id: value.id,
        name: value.name,
        text: value.text,
        isActive: value.isActive,
        rating: value.rating,
        location: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.location)),
        avatar: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    order: bigint;
    caption: [] | [string];
    category: [] | [string];
    image: _ExternalBlob;
}): Promise<{
    id: bigint;
    order: bigint;
    caption?: string;
    category?: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        order: value.order,
        caption: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.caption)),
        category: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.category)),
        image: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    order: bigint;
    caption: [] | [string];
    image: _ExternalBlob;
}): Promise<{
    id: bigint;
    order: bigint;
    caption?: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        order: value.order,
        caption: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.caption)),
        image: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    highlights: Array<string>;
    heroImage: [] | [_ExternalBlob];
    bookingUrl: [] | [string];
    location: string;
}): Promise<{
    id: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    highlights: Array<string>;
    heroImage?: ExternalBlob;
    bookingUrl?: string;
    location: string;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        amenities: value.amenities,
        highlights: value.highlights,
        heroImage: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.heroImage)),
        bookingUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.bookingUrl)),
        location: value.location
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    thumbnail: [] | [_ExternalBlob];
    pricePerNight: [] | [string];
    name: string;
    description: string;
    propertyId: bigint;
    amenities: Array<string>;
    capacity: [] | [string];
}): Promise<{
    id: bigint;
    thumbnail?: ExternalBlob;
    pricePerNight?: string;
    name: string;
    description: string;
    propertyId: bigint;
    amenities: Array<string>;
    capacity?: string;
}> {
    return {
        id: value.id,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.thumbnail)),
        pricePerNight: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.pricePerNight)),
        name: value.name,
        description: value.description,
        propertyId: value.propertyId,
        amenities: value.amenities,
        capacity: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.capacity))
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: _ContactInfo;
    socialLinks: Array<_SocialLink>;
    logo: [] | [_ExternalBlob];
    bookingUrl: [] | [string];
    footerText: string;
}): Promise<{
    contactInfo: ContactInfo;
    socialLinks: Array<SocialLink>;
    logo?: ExternalBlob;
    bookingUrl?: string;
    footerText: string;
}> {
    return {
        contactInfo: from_candid_ContactInfo_n42(_uploadFile, _downloadFile, value.contactInfo),
        socialLinks: value.socialLinks,
        logo: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.logo)),
        bookingUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.bookingUrl)),
        footerText: value.footerText
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    whatsapp: [] | [string];
    email: string;
    address: string;
    phone: string;
}): {
    whatsapp?: string;
    email: string;
    address: string;
    phone: string;
} {
    return {
        whatsapp: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.whatsapp)),
        email: value.email,
        address: value.address,
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimonial>): Promise<Array<Testimonial>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Testimonial_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryImage>): Promise<Array<GalleryImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryImage_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HeroSlide>): Promise<Array<HeroSlide>> {
    return await Promise.all(value.map(async (x)=>await from_candid_HeroSlide_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Promise<Array<Property>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Property_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoomType>): Promise<Array<RoomType>> {
    return await Promise.all(value.map(async (x)=>await from_candid_RoomType_n38(_uploadFile, _downloadFile, x)));
}
async function to_candid_AboutUsContent_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AboutUsContent): Promise<_AboutUsContent> {
    return await to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_ContactInfo_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactInfo): _ContactInfo {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_GalleryImage_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryImage): Promise<_GalleryImage> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_HeroSlide_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeroSlide): Promise<_HeroSlide> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_Property_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Property): Promise<_Property> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_RoomType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): Promise<_RoomType> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_SiteSettings_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteSettings): Promise<_SiteSettings> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_Testimonial_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Testimonial): Promise<_Testimonial> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    order: bigint;
    caption?: string;
    image: ExternalBlob;
}): Promise<{
    id: bigint;
    order: bigint;
    caption: [] | [string];
    image: _ExternalBlob;
}> {
    return {
        id: value.id,
        order: value.order,
        caption: value.caption ? candid_some(value.caption) : candid_none(),
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    highlights: Array<string>;
    heroImage?: ExternalBlob;
    bookingUrl?: string;
    location: string;
}): Promise<{
    id: bigint;
    name: string;
    description: string;
    amenities: Array<string>;
    highlights: Array<string>;
    heroImage: [] | [_ExternalBlob];
    bookingUrl: [] | [string];
    location: string;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        amenities: value.amenities,
        highlights: value.highlights,
        heroImage: value.heroImage ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.heroImage)) : candid_none(),
        bookingUrl: value.bookingUrl ? candid_some(value.bookingUrl) : candid_none(),
        location: value.location
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    thumbnail?: ExternalBlob;
    pricePerNight?: string;
    name: string;
    description: string;
    propertyId: bigint;
    amenities: Array<string>;
    capacity?: string;
}): Promise<{
    id: bigint;
    thumbnail: [] | [_ExternalBlob];
    pricePerNight: [] | [string];
    name: string;
    description: string;
    propertyId: bigint;
    amenities: Array<string>;
    capacity: [] | [string];
}> {
    return {
        id: value.id,
        thumbnail: value.thumbnail ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.thumbnail)) : candid_none(),
        pricePerNight: value.pricePerNight ? candid_some(value.pricePerNight) : candid_none(),
        name: value.name,
        description: value.description,
        propertyId: value.propertyId,
        amenities: value.amenities,
        capacity: value.capacity ? candid_some(value.capacity) : candid_none()
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    text: string;
    isActive: boolean;
    rating: bigint;
    location?: string;
    avatar?: ExternalBlob;
}): Promise<{
    id: bigint;
    name: string;
    text: string;
    isActive: boolean;
    rating: bigint;
    location: [] | [string];
    avatar: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        name: value.name,
        text: value.text,
        isActive: value.isActive,
        rating: value.rating,
        location: value.location ? candid_some(value.location) : candid_none(),
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    mission?: string;
    teamImage?: ExternalBlob;
    vision?: string;
}): Promise<{
    title: string;
    content: string;
    mission: [] | [string];
    teamImage: [] | [_ExternalBlob];
    vision: [] | [string];
}> {
    return {
        title: value.title,
        content: value.content,
        mission: value.mission ? candid_some(value.mission) : candid_none(),
        teamImage: value.teamImage ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.teamImage)) : candid_none(),
        vision: value.vision ? candid_some(value.vision) : candid_none()
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: ContactInfo;
    socialLinks: Array<SocialLink>;
    logo?: ExternalBlob;
    bookingUrl?: string;
    footerText: string;
}): Promise<{
    contactInfo: _ContactInfo;
    socialLinks: Array<_SocialLink>;
    logo: [] | [_ExternalBlob];
    bookingUrl: [] | [string];
    footerText: string;
}> {
    return {
        contactInfo: to_candid_ContactInfo_n48(_uploadFile, _downloadFile, value.contactInfo),
        socialLinks: value.socialLinks,
        logo: value.logo ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.logo)) : candid_none(),
        bookingUrl: value.bookingUrl ? candid_some(value.bookingUrl) : candid_none(),
        footerText: value.footerText
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    whatsapp?: string;
    email: string;
    address: string;
    phone: string;
}): {
    whatsapp: [] | [string];
    email: string;
    address: string;
    phone: string;
} {
    return {
        whatsapp: value.whatsapp ? candid_some(value.whatsapp) : candid_none(),
        email: value.email,
        address: value.address,
        phone: value.phone
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    order: bigint;
    caption?: string;
    category?: string;
    image: ExternalBlob;
}): Promise<{
    id: bigint;
    order: bigint;
    caption: [] | [string];
    category: [] | [string];
    image: _ExternalBlob;
}> {
    return {
        id: value.id,
        order: value.order,
        caption: value.caption ? candid_some(value.caption) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
